name: Build for Windows

on:
  - push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.0.0'
          arch: win64_mingw81
      - name: Compile App
        run: lrelease WebcamDownloader.pro && qmake && make
      - name: Create Deployment Dir
        run: mkdir ..\WebcamDownloader-Release && mv release\WebcamDownloader.exe ..\WebcamDownloader-Release && windeployqt --qmldir . ..\WebcamDownloader-Release\WebcamDownloader.exe && cp dependencies\* ..\WebcamDownloader-Release
      - name: Install InnoSetup & 7zip
        run: choco install -y innosetup 7zip
      - name: Create Installer
        run: iscc setupscript.iss && mv ..\WebcamDownloaderSetup.exe .
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: WebcamDownloader
          path: WebcamDownloaderSetup.exe
